server:
  port: 8321
  context-path: /
  session:
    timeout: -1

spring:
  datasource:
    url: jdbc:mysql://14.116.219.64:3306/ai?useUnicode=true&characterEncoding=utf-8
    username: jdrobot
    password: Jd!@#9257
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  devtools:
    restart:
      enabled: true  #设置开启热部署

  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  thymeleaf:
    cache: false  #如果开启此处会导致每次输入删除都会自动刷新哪怕你没保存
    templates_root: src/main/resources/templates/
    prefix: classpath:/templates/
    content-type: text/html
    check-template-location: true
    suffix: .html
    mode: LEGACYHTML5

  http:
    multipart:
      max-file-size: 600Mb
      max-request-size: 600Mb

#  shell 命令参数
shell:
  path: /bin/sh
  str: -c

python:
  ip: 39.108.114.251
  baseUrl: /home/cw/code
  path1: python3 ${python.baseUrl}/dianbiao_crnn/dianbiao.py  #电表识别程序
  path2: python3 ${python.baseUrl}/fengedan/main.py  #分割单程序

#产生随机值
secret: ${random.value}